// Code generated by MockGen. DO NOT EDIT.
// Source: main.go

// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	models "github.com/bdronneau/memoriesbox/pkg/repositories/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockApp is a mock of App interface.
type MockApp struct {
	ctrl     *gomock.Controller
	recorder *MockAppMockRecorder
}

// MockAppMockRecorder is the mock recorder for MockApp.
type MockAppMockRecorder struct {
	mock *MockApp
}

// NewMockApp creates a new mock instance.
func NewMockApp(ctrl *gomock.Controller) *MockApp {
	mock := &MockApp{ctrl: ctrl}
	mock.recorder = &MockAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApp) EXPECT() *MockAppMockRecorder {
	return m.recorder
}

// CountMemories mocks base method.
func (m *MockApp) CountMemories() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountMemories")
	ret0, _ := ret[0].(int64)
	return ret0
}

// CountMemories indicates an expected call of CountMemories.
func (mr *MockAppMockRecorder) CountMemories() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountMemories", reflect.TypeOf((*MockApp)(nil).CountMemories))
}

// GetRandomMemories mocks base method.
func (m *MockApp) GetRandomMemories() (models.Memory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandomMemories")
	ret0, _ := ret[0].(models.Memory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRandomMemories indicates an expected call of GetRandomMemories.
func (mr *MockAppMockRecorder) GetRandomMemories() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandomMemories", reflect.TypeOf((*MockApp)(nil).GetRandomMemories))
}

// PingDB mocks base method.
func (m *MockApp) PingDB() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PingDB")
	ret0, _ := ret[0].(error)
	return ret0
}

// PingDB indicates an expected call of PingDB.
func (mr *MockAppMockRecorder) PingDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PingDB", reflect.TypeOf((*MockApp)(nil).PingDB))
}
